build:
  - .github/**/*

scripts:
  - buildSrc/src/main/kotlin/**/script/**/*.kts

dependencies:
  - buildSrc/**/*
  - gradlePlugin/**/*

documentation:
  - docs/**/*
  - README.adoc
  - LICENSE
  - CHANGELOG.adoc
  - CODE-OF-CONDUCT.adoc
  - CONTRIBUTION.adoc
  - readmeOSS.adoc

# Library
example-android-application:
  - example-android-application/**/*

kmp-lib:
  - kmp-lib/**/*
